# Generated by Django 4.2.4 on 2023-08-31 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='page_description',
        ),
    ]
