# Generated by Django 4.2.4 on 2023-08-31 19:14

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_body_homepage_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
